// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerzekeringApi.Data;

#nullable disable

namespace VerzekeringApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260109120744_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("VerzekeringApi.Models.Klant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BeginDatum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EindDatum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Geboortedatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tussenvoegsel")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Woonplaats")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Klanten");
                });

            modelBuilder.Entity("VerzekeringApi.Models.Opstalverzekering", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AanvullendeOpties")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BeginDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Betaaltermijn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EindDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("GedekteGebeurtenissen")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Herbouwwaarde")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("Inboedelwaarde")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("KlantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PolisNummer")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Premie")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("TypeDekking")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT");

                    b.Property<string>("Uitsluitingen")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.HasIndex("PolisNummer")
                        .IsUnique();

                    b.ToTable("Opstalverzekeringen");
                });

            modelBuilder.Entity("VerzekeringApi.Models.Opstalverzekering", b =>
                {
                    b.HasOne("VerzekeringApi.Models.Klant", "Klant")
                        .WithMany("Opstalverzekeringen")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klant");
                });

            modelBuilder.Entity("VerzekeringApi.Models.Klant", b =>
                {
                    b.Navigation("Opstalverzekeringen");
                });
#pragma warning restore 612, 618
        }
    }
}
